### ISSUE TITLE
block feature 

### ISSUE THREAD

**Issue by derram** [flare561/berry#12]
Needs the block feature reimplemented to prevent responding to other bots.

Also missing a lot of code from previous versions.

**Comment by flare561** [comment]
Not sure about adding it to the main codebase, maybe just a list on config.json of nicks to ignore, certainly not the ~ignore command from the old codebase. Too much effort for too little use. For now the workaround replacing line 12 in main.py with

`if not event.source in [self.nickname, 'other', 'nicks', 'to', 'ignore']:`

I'm going to close the issue and think about adding it to the codebase when I do my next round of refactoring.
